export const presetClothes = [
    {
        id: 1,
        name: "blue shirt",
        img: 'https://www.bulkapparel.com/image/fashion-wear/105366_f_fm.jpg',
        type: "top",
        filters: {
            cozy: true,
            formal: false,
            temphigh: 80,
            templow: 60,
        },
        clean: true,
    },
    {
        id: 2,
        name: "black sweat pants",
        img: 'https://s7d7.scene7.com/is/image/GTMSportswear/70048BU-1?qlt=80,0&resMode=sharp2&fmt=png-alpha&hei=500&wid=500&layer=1&op_colorize=181818',
        type: "bottom",
        filters: {
            cozy: true,
            formal: false,
            temphigh: 70,
            templow: 40,
        },
        clean: true,
    },
    {
        id: 3,
        name: "tan sweater",
        img: 'https://www.outerknown.com/cdn/shop/products/1410077_SHELTER_WAFFLE_CREW_HCM_1.jpg?v=1676329554',
        type: "top",
        filters: {
            cozy: true,
            formal: true,
            temphigh: 60,
            templow: 30,
        },
        clean: true,
    },
    {
        id: 4,
        name: "dark jeans",
        img: 'https://www.gap.com/webcontent/0056/081/447/cn56081447.jpg',
        type: "bottom",
        filters: {
            cozy: false,
            formal: true,
            temphigh: 70,
            templow: 30,
        },
        clean: true,
    },
    {
        id: 5,
        name: "black shirt",
        img: 'https://us.sunspel.com/cdn/shop/files/mtsh0181-bkaa-1.jpg?v=1720096619',
        type: "top",
        filters: {
            cozy: true,
            formal: false,
            temphigh: 80,
            templow: 60,
        },
        clean: true,
    },
    {
        id: 6,
        name: "khaki pants",
        img: 'https://www.untuckit.com/cdn/shop/files/ST-CLAIR-UNTUCKIT-41850Tan-PANTS-SOLID-KHAKI-3.jpg?height=1000&v=1713300464',
        type: "bottom",
        filters: {
            cozy: false,
            formal: true,
            temphigh: 70,
            templow: 30,
        },
        clean: true,
    },
    {
        id: 7,
        name: "red crewneck",
        img: 'https://www.bobbarker.com/Website%20Images/SWEATSHIRTSZ_Main!01.jpg',
        type: "top",
        filters: {
            cozy: true,
            formal: false,
            temphigh: 60,
            templow: 30,
        },
        clean: true,
    },
    {
        id: 8,
        name: "gray sweatpants",
        img: 'https://media.istockphoto.com/id/1314274760/photo/sport-pants.jpg?s=612x612&w=0&k=20&c=2siBA_21V8CbWXUfQ7ttUqW7ZOzs_d2yjSK8jEtvLw4=',
        type: "bottom",
        filters: {
            cozy: true,
            formal: false,
            temphigh: 70,
            templow: 40,
        },
        clean: true,
    },

]